# Generated by Django 2.2.4 on 2019-08-19 00:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='todo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todos.Todo'),
            preserve_default=False,
        ),
    ]
